version: '3'
services:
  php:
    container_name: "php"
    image: bitnami/php-fpm:8.1
    volumes:
      - ./:/app:delegated
      - ./docker/php/php.ini:/opt/bitnami/php/etc/conf.d/php.ini:ro

  # --- Apache 2.4
  apache:
    container_name: "apache"
    image: bitnami/apache:2.4
    ports:
      - "8383:8080"
    depends_on:
      - php
    volumes:
      - ./:/app:delegated
      - ./docker/apache/vhost.conf:/vhosts/myapp.conf:ro
