security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    alice: { password: password, roles: "ROLE_WRITTER" }
                    spellchecker: { password: password , roles: "ROLE_SPELLCHECKED" }
                    journalist: { password: password , roles: "ROLE_JOURNALIST" }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            logout: true
            switch_user:
                role: IS_AUTHENTICATED_ANONYMOUSLY
