framework:
    workflows:
        article:
            marking_store:
                type: property_accessor
            supports:
                - AppBundle\Entity\Article
            places:
                - draft
                - wait_for_journalist
                - approved_by_journalist
                - wait_for_spellchecker
                - approved_by_spellchecker
                - published
            transitions:
                request_review:
                    from:
                        - draft
                    to:
                        - wait_for_journalist
                        - wait_for_spellchecker
                journalist_approval:
                    from:
                        - wait_for_journalist
                    to:
                        - approved_by_journalist
                spellchecker_approval:
                    from:
                        - wait_for_spellchecker
                    to:
                        - approved_by_spellchecker
                publish:
                    from:
                        - approved_by_journalist
                        - approved_by_spellchecker
                    to:
                        - published

        # Another workflow, in French, for the SFLive Paris 2016
        article_fr:
            marking_store:
                type: property_accessor
            supports:
                - stdClass # Just a hack
            places:
                - brouillon
                - attente_journaliste
                - journaliste OK
                - attente correcteur
                - correcteur OK
                - publié

            transitions:

                demande relecture:
                    from:
                        - brouillon
                    to:
                        - attente_journaliste
                        - attente correcteur
                journaliste approuve:
                    from:
                        - attente_journaliste
                    to:
                        - journaliste OK
                correcteur approuve:
                    from:
                        - attente correcteur
                    to:
                        - correcteur OK
                publication:
                    from:
                        - journaliste OK
                        - correcteur OK
                    to:
                        - publié
