parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            Symfony\Component\Workflow\StateMachine $trafficLightStateMachine: '@state_machine.traffic_light'
            Symfony\Component\Workflow\StateMachine $signupStateMachine: '@state_machine.signup'
            Symfony\Component\Workflow\Workflow $articleWorkflow: '@workflow.article'

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    state_machine.traffic_light_php:
        public: true
        class: Symfony\Component\Workflow\StateMachine
        factory: [App\Workflow\TrafficLightFactory, create]

    state_machine.traffic_light_messenger:
        public: true
        class: Symfony\Component\Workflow\StateMachine
        arguments:
            - '@state_machine.traffic_light.definition'
            - ~
            - '@App\Workflow\EventDispatcher'

sensio_framework_extra:
    router:
        annotations: false

framework:
    workflows:
        traffic_light:
            supports: App\Entity\TrafficLight
            marking_store:
                type: 'method'
                property: 'state'
            places:
                - green
                - yellow
                - red
            transitions:
                to_green:
                    from: yellow
                    to: green
                to_yellow_foo:
                    name: to_yellow
                    from: green
                    to: yellow
                to_yellow_bar:
                    name: to_yellow
                    from: red
                    to: yellow
                to_red:
                    from: yellow
                    to: red
